docs/import/import-files/avro.md
docs/import/import-files/delimited-text.md
docs/import/import-files/orc.md
docs/import/import-files/parquet.md
docs/import/import-jdbc.md
flux-cli/build.gradle
flux-cli/src/main/java/com/marklogic/flux/api/WriteStructuredDocumentsOptions.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportJdbcTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportParquetFilesTest.java
flux-cli/src/test/resources/delimited-files/empty-values.csv
mlcp-testing/build.gradle

The default of our connector is to retain null fields when using a Spark data source. So the user now has a `--ignore-null-fields` option.

Can now ignore null fields

---

docs/common-options.md
docs/copy.md
docs/export/custom-export.md
docs/export/export-archives.md
docs/export/export-documents.md
docs/export/export-rdf.md
docs/export/export-rows.md
docs/export/export.md
docs/export/specifying-path.md
docs/import/common-import-features.md
docs/import/custom-import.md

Also fixed tables where the options weren't in tick marks. The docs HTML was turning "--" into "-".

Fixes for export docs

---

docs/common-options.md
docs/import/import-files/selecting-files.md
flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ReadFilesParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateXmlFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
flux-cli/src/test/resources/options-files/import-people-files.txt

I think with the switch to picocli, wildcards started getting resolved in a shell environment before being sent to picocli. That requires the `--path` option to be given an arity of `1..*` to accept multiple values. Updated the docs to better capture this.
Also added docs on connection type.

Path option now properly supports wildcards

---

docs/common-options.md
flux-cli/src/dist/conf/log4j2.properties
flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/main/java/com/marklogic/flux/impl/CommonParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
flux-cli/src/test/java/com/marklogic/flux/impl/ShowSparkProgressBarTest.java

The Spark progress console writes to stderr and thus complicates life if you want to use `2>&1` to mix stderr/stdout logging. It also doesn't help much at all for import/copy/reprocess.

Added --spark-show-progress-bar to make it conditional

---

caddy/config/Caddyfile
docs/common-options.md
docs/import/common-import-features.md
docs/reprocess.md
flux-cli/src/main/java/com/marklogic/flux/api/RdfFilesExporter.java
flux-cli/src/main/java/com/marklogic/flux/api/ReadDocumentsOptions.java
flux-cli/src/main/java/com/marklogic/flux/api/ReadRowsOptions.java
flux-cli/src/main/java/com/marklogic/flux/api/WriteDocumentsOptions.java
flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportRdfFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadDocumentParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadRowsParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/reprocess/ReprocessCommand.java
flux-cli/src/test/java/com/marklogic/flux/impl/ExportRdfFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/copy/CopyOptionsTest.java

log-progress is now discussed in the "Common Options" section. 
Next PR will remove the Spark progress bar as an option.

Added log-progress for export commands

---

docs/common-options.md
docs/reprocess.md
flux-cli/src/test/java/com/marklogic/flux/impl/reprocess/ReprocessTest.java
test-app/src/main/ml-modules/root/writeBatch.sjs

Added a test for writing a batch of URIs. We know it works already via the connector, but wanted to have it handy for reference here.

MLE-15663 Improved docs for reprocessing

---

NOTICE.txt
docs/spark-integration.md
flux-cli/build.gradle

This avoids a high CVE. Added notes to build.gradle to capture exactly what's going on.
Also updated Spark from 3.4.1 to 3.4.3. This has very little impact, which is expected as the bump to 3.4.3 for the connector project did not result in any failed tests.

Updated hadoop to 3.3.6 again

---

docs/common-options.md
docs/getting-started.md
flux-cli/build.gradle
flux-cli/scripts/README.md
flux-cli/scripts/original-start-script-windows.txt
flux-cli/scripts/start-script-windows.txt
flux-cli/scripts/start-script.txt

Using a wildcard for the classpath both fixes the issue with an overly long classpath on Windows and also makes it easy to include everything in "ext".
Also added a missing docs section for JVM options.

MLE-15766 Fixing issues with executable on Windows

---

docs/common-options.md
flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportDelimitedFilesCommandTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
flux-cli/src/test/resources/options-files/export-rows.txt

Not sure why I had this set to the "simple" format before, as we absolutely want to allow newline symbols.

Allowing for newline symbols in values in options files

---

build.gradle
docs/getting-started.md

We do the same thing for our Spark connector, and it's simpler vs telling a user to clone the repository.

Packaging up the getting started project to include in release

---

docs/reprocess.md
flux-cli/build.gradle
flux-cli/src/test/java/com/marklogic/flux/impl/reprocess/ReprocessTest.java

We may run into other issues like this - i.e. error scenarios that aren't yet tested where Spark does something as part of the error that requires an "--add-opens" that we don't yet have registered.
Enhanced docs on invokes as well.

Fixing a small issue with Java 17 and a certain reprocess error

---

flux-cli/build.gradle
flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/test/java/com/marklogic/flux/impl/reprocess/ReprocessTest.java

Spark sometimes includes the stacktrace in the exception message, which is a bad UX for a user that hasn't asked to see a stacktrace. Doing a pretty basic check to detect this scenario and only print the actual error message.

Removing stacktrace from exception message

---

CONTRIBUTING.md
flux-cli/build.gradle

Haven't found a way to force the use of Java 17 yet, and we only need it here, not for the whole project. It is possible that we could require Java 17 for all tasks, with Java 11 still being the level that the code is compiled at.

Added note about running updateJavadoc

---

flux-cli/build.gradle
flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesExporter.java
flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesImporter.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ImportFilesCommand.java
flux-cli/src/test/java/com/marklogic/flux/api/GenericFilesImporterTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
gradle.properties

This is largely just declaring `--streaming` and ensuring it's sent to the connector correctly.

MLE-17041 Added streaming option for importing and exporting files

---

docker-compose.yml
docs/export/export-archives.md
docs/export/export-documents.md
docs/export/export-rdf.md
docs/getting-started.md
docs/import/common-import-features.md
docs/import/import-files/aggregate-xml.md
docs/import/import-files/avro.md
docs/import/import-files/delimited-text.md
docs/import/import-files/generic-files.md
docs/import/import-files/json.md
docs/import/import-files/orc.md
docs/import/import-files/parquet.md
docs/import/import-files/rdf.md
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportFilesCommand.java
flux-cli/src/test/java/com/marklogic/flux/api/GenericFilesExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateJsonFilesTest.java

Also made use of "ZIP" and "gzip" consistent in the docs and the tests.
And bumped the docker-compose file to use the official MarkLogic images.
Otherwise, no functional changes here, just docs.

MLE-17142 Added docs for gzip streaming

---

CONTRIBUTING.md
flux-cli/build.gradle
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesTest.java

All tests passing in both the connector project and Flux repo. Verified manually with spark-submit too.

Bumped to Spark 3.5.3

---

flux-cli/build.gradle
flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportRdfFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadDocumentParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/ExportRdfFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/copy/CopyOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportRdfFilesOptionsTest.java
gradle.properties

For commands that export documents and don't necessarily need a consistent snapshot.

MLE-17429 Added --no-snapshot

---

flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ImportFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParamsImpl.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportRdfFilesTest.java

This is more to simplify the import command hierarchy and also the import API hierarchy. There's no technical issue with splitting on managed triples documents, it just won't likely be used, but that's fine.

Making splitter available on all import commands

---

docs/import/splitting.md
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateXmlFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportArchiveFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportMlcpArchiveFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportRdfFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/splitter/ImportAndSplitFilesTest.java

Decided to rename "splitter-xml-path" to "splitter-xml-xpath" to make it obvious that it's XPath and that it's only intended for XML and not JSON.

MLE-17497 First batch of splitter docs

---

docs/copy.md
docs/import/common-import-features.md
docs/import/splitting.md
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java

Decided to rename "splitter-output" to "splitter-sidecar" since all the options are specific to sidecar documents. Probably going to rename the options in the connector too, which will then force changes here too.

MLE-17497 Wrapped up splitter docs

---

docs/import/splitting.md
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/splitter/ImportAndSplitFilesTest.java

This is consistent with other map params that accept custom key/value pairs.

Renamed --splitter-custom-option to -S

---

flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/test/java/com/marklogic/flux/impl/ConfigureSparkMasterUrlTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/HandleErrorTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportAvroFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportJdbcTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateJsonFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateXmlFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportArchiveFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAvroFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportJdbcTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportMlcpArchiveFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportParquetFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportRdfFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/splitter/ImportAndSplitFilesTest.java

Changed the formatting of generic errors, which affected a lot of tests in a small way.

MLE-17733 Providing additional context for JDBC error messages

---

flux-cli/src/test/java/com/marklogic/flux/api/CustomRowsExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/api/DelimitedFilesExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/custom/CustomExportRowsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportDelimitedFilesCommandTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/embedder/ImportFilesWithEmbedderTest.java
flux-cli/src/test/resources/options-files/export-rows.txt

No idea why these aren't failing on Jenkins, which is a separate issue. But these tests all had a legit failure - Spark was complaining that a BINARY column type wasn't supported by the Spark CSV data source. So these tests don't include the "base64Binary" column that has a type of BINARY.

Fixing CSV test errors

---

docs/export/export-archives.md
docs/export/export-documents.md
docs/export/export-rdf.md
flux-cli/src/main/java/com/marklogic/flux/impl/OptionsUtil.java
flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/custom/CustomExportDocumentsCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportArchiveFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportRdfFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadDocumentParams.java
flux-cli/src/test/java/com/marklogic/flux/api/ArchiveFilesExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/api/CustomDocumentsExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/api/DocumentCopierTest.java
flux-cli/src/test/java/com/marklogic/flux/api/GenericFilesExporterTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/ExportRdfFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java

This is specific to export operations and resulted in a number of test cases being removed, as the user no longer gets an error if they don't specify any query.

MLE-17915 Using a "true query" if user does not specify a query

---

CONTRIBUTING.md
flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/test/java/com/marklogic/flux/AbstractTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/HandleErrorTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/HelpTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java

Added a public `run` method that returns the code for tests to call, while `main` actually makes the `System.exit` call.
Manually verified that spark-submit still works too (we don't want to call System.exit there).

MLE-19129 Flux now returns the exit code

---

docs/reprocess.md
flux-cli/src/main/java/com/marklogic/flux/api/Executor.java
flux-cli/src/main/java/com/marklogic/flux/api/Reprocessor.java
flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/CommonParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/JdbcUtil.java
flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
flux-cli/src/main/java/com/marklogic/flux/impl/reprocess/ReprocessCommand.java
flux-cli/src/test/java/com/marklogic/flux/api/ReprocessorTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/reprocess/ReprocessOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/reprocess/ReprocessTest.java

Added `--thread-count` as an alias for `--repartitions` so a user can just think about threads. Both have the same effect now, which is to set the Spark master URL to have a number of threads equivalent to the number of partitions.

MLE-19164 Defaulting Spark master URL based on reprocessor threads

---

.gitignore
docs/common-options.md
docs/export/export-documents.md
docs/export/export-rows.md
docs/import/tuning-performance.md
docs/reprocess.md
flux-cli/src/main/java/com/marklogic/flux/api/Flux.java
flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
flux-cli/src/main/java/com/marklogic/flux/impl/custom/CustomExportRowsCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/AbstractExportRowsToFilesCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportJdbcCommand.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadDocumentParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/export/ReadRowsParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/reprocess/ReprocessCommand.java
flux-cli/src/test/java/com/marklogic/flux/impl/custom/CustomExportRowsOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportArchiveFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportJdbcOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportJsonLinesFilesOptionsTest.java

This is for export operations using Optic, where the user is able to specify the number of partitions.
Updated the docs as well, though I'm thinking the docs could use a scrub soon to iron out the subtleties between "partitions" and "Spark threads" and "partition threads".
And - fixed a gitignore issue that had hidden a couple of export tests. Odd.

MLE-19164 Configuring Spark master URL based on partition count

---

build.gradle
flux-cli/build.gradle
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ExtractTextTest.java
flux-java17-tests/build.gradle
flux-tests-api/build.gradle

Next PR will be to remove the Tika libraries as implementation dependencies so that they're included in the zip but not in the API dependency.

MLE-19898 Can now extract from Microsoft files

---

flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesImporter.java
flux-cli/src/main/java/com/marklogic/flux/impl/ConnectionInputs.java
flux-cli/src/main/java/com/marklogic/flux/impl/ConnectionParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/ConnectionString.java
flux-cli/src/main/java/com/marklogic/flux/impl/copy/OutputConnectionParams.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ImportFilesCommand.java
flux-tests-api/build.gradle

Started this branch with adding the necessary extraction options to the API.
Then modified it to not have to compile against the Java Client, which is now fully shadowed in the marklogic-spark-connector.

Added extraction options, and no longer compiling against Java Client

---

NOTICE.txt
build.gradle
docs/spark-integration.md
flux-cli/build.gradle

Should be a no-op in terms of functionality, but does bump a few transitive dependencies up.

Bumped Spark from 3.5.3 to 3.5.5

---

flux-embedding-model-azure-open-ai/build.gradle
flux-embedding-model-minilm/build.gradle
flux-embedding-model-ollama/build.gradle
gradle.properties

Unfortunately only the main library is on 1.0.0-rc1 while the others are still on 1.0.0-beta4.

Bumping langchain4j

---

flux-cli/src/main/java/com/marklogic/flux/impl/reprocess/ReprocessCommand.java

I think I did a List initially so I could provide custom error messages. But the default error messages from picocli for mismatched key/value pairs with a Map param are good enough - they identify the bad param, which is enough for the user to fix the problem. So this gets rid of some code.

MLE-21726 Refactor - switching from List to Map for var params

---

flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SparkColumnIterator.java
flux-cli/src/main/java/com/marklogic/flux/tde/TdeInputs.java
flux-java17-tests/src/test/java/com/marklogic/flux/tde/AbstractTdeTest.java
flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildJsonTdeTest.java
flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildXmlTdeTest.java

This ensures the TDE can be loaded without error.
Also did a simple move of SparkColumnIterator to a spark-specific package.

MLE-21825 Improved unit tests to load TDE

---

flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SparkColumnIterator.java
flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
flux-cli/src/main/java/com/marklogic/flux/tde/JsonTdeBuilder.java
flux-cli/src/main/java/com/marklogic/flux/tde/TdeBuilder.java
flux-cli/src/main/java/com/marklogic/flux/tde/TdeInputs.java
flux-cli/src/main/java/com/marklogic/flux/tde/XmlTdeBuilder.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesOptionsTest.java
flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildJsonTdeTest.java
flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildXmlTdeTest.java

And I'm now curious to see what comments GitHub Copilot makes about the code that VSCode Copilot generated.
Summary from Copilot:
The refactoring journey we just completed was really satisfying:
Started with duplicated column customization logic scattered across JsonTdeBuilder and XmlTdeBuilder
Moved all the logic into the Column interface methods in SparkColumn
Renamed everything to use consistent "permissions" terminology (matching MarkLogic's naming)
Upgraded from String[] to Set<String> for better type safety and consistency
Centralized the comma-splitting logic in WriteStructuredDocumentParams where it belongs
Now the code is much more maintainable - all column customization logic lives in one place (SparkColumn), the builders are clean and focused, and everything uses consistent …

MLE-21825 Refactored TDE generator with my good friend Copilot

---

flux-cli/build.gradle
flux-embedding-model-azure-open-ai/build.gradle
flux-embedding-model-minilm/build.gradle
flux-embedding-model-ollama/build.gradle
gradle.properties

This avoids a potential nasty error message. Also TIL we don't need to relocate the Netty classes for the Azure embedding model given that Flux is already using the same Netty version courtesy of Azure Storage jars.

MLE-23170 Defaulting to Netty's pure Java SSL

---

flux-cli/src/main/java/com/marklogic/flux/impl/ConnectionParams.java
flux-cli/src/test/java/com/marklogic/flux/impl/ConnectionParamsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java

All connection params can now be set via system properties.  Not documenting this yet, as the main use case is for an internal project.

MLE-23506 Exposing connection params as system properties

---

flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/test/java/com/marklogic/flux/impl/AbstractOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/custom/CustomExportRowsOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportJdbcOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateJsonFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateXmlFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportArchiveFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAvroFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportMlcpArchiveFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportOrcFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportParquetFilesOptionsTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportRdfFilesOptionsTest.java

This is for ragplus, so that a custom Spark session - specifically with a Spark listener - can be used to execute the command.
This also ended up being a better approach for our "options tests" that just need to parse options but not execute the command. So about a dozen tests were modified to use this approach. They also needed a connection string added since the command is being validated now too.

MLE-23618 Added new Main method to return a Command object

---

flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
flux-tests-api/src/main/resources/log4j2.properties

This appears to be the better way to apply Spark config params, such that we likely don't need both -B and -C any more. I opened a ticket to figure that one out.

MLE-23884 Better approach for configuring SparkConf

---

build.gradle
docs/api.md
examples/client-project/build.gradle

Spark 4.0.1 wants 2.18.2, verified all is fine via the example client project.

MLE-23024 Updating Jackson to 2.18.2

---

build.gradle
flux-cli/build.gradle
flux-cli/src/test/java/com/marklogic/flux/impl/OverrideSparkConfTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAvroFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportOrcFilesTest.java
flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportParquetFilesTest.java
gradle.properties

Using constraints as well to ensure the pom.xml file contains the same dependency updates.
Spark 4.1.0 is using io.netty 4.1.122 - not changing that for now, need to see what Black Duck thinks.

MLE-23024 Bumping to Spark 4.1.0 preview1
