- flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/reprocess/ReprocessCommand.java
The connector now defaults to zero.
> Setting default value for log-progress to 10000

- docs/import/import-files/delimited-text.md
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesTest.java
- flux-cli/src/test/resources/delimited-files/multi-line.txt
No functional change, just making sure it works.
> Added test and docs note for multiline CSV files

- build.gradle
- flux-cli/build.gradle
Still planning on a 2.3.0 release, just want to see Jenkins go green for this.
> Bumped to 2.3.0.rc1

- CONTRIBUTING.md
- README.md
- docs/getting-started.md
- docs/index.md
- docs/spark-integration.md
- examples/client-project/build.gradle
- flux-cli/build.gradle
- gradle.properties
Not pulling trigger yet, just getting things ready.
> Prepping for 1.0.0

- CONTRIBUTING.md
- flux-cli/build.gradle
We will have a Jenkins job soon for verifying the tests on Java 17.
> Added JVM options for running on Java 17

- docs/spark-integration.md
- flux-cli/build.gradle
Using any mixture of Hadoop versions produces bugs. Added docs on the CVE.
> MLE-15771 Standardizing on Hadoop 3.3.4

- docs/export/export-rows.md
- flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/AbstractExportRowsToFilesCommand.java
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportParquetFilesTest.java
> MLE-15775 Disabling Spark success and checksum files

- flux-cli/src/dist/conf/log4j2.properties
See the description in the logging file.
> Quieting down some Windows-specific errors

- docs/api.md
- docs/common-options.md
- docs/copy.md
- docs/export/custom-export.md
- docs/export/export-archives.md
- docs/export/export-documents.md
- docs/export/export-rdf.md
- docs/export/export-rows.md
- docs/export/specifying-path.md
- docs/import/aggregating-rows.md
- docs/import/custom-import.md
- docs/import/import-files/aggregate-xml.md
- docs/import/import-files/archives.md
- docs/import/import-files/avro.md
- docs/import/import-files/delimited-text.md
- docs/import/import-files/generic-files.md
- docs/import/import-files/json.md
- docs/import/import-files/orc.md
- docs/import/import-files/parquet.md
- docs/import/import-files/rdf.md
- docs/import/import-files/selecting-files.md
- docs/import/import-jdbc.md
- docs/reprocess.md
- docs/spark-integration.md
No functional changes, just code tabs, and a couple docs fixes too.
> MLE-16185 Converted other docs to use code tabs

- docs/common-options.md
Directing this to master to address a GH ticket from yesterday.
> MLE-16385 Added docs on configuring SSL for Flux

- docs/export/export-documents.md
- docs/import/common-import-features.md
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java
- test-app/src/main/ml-config/security/roles/flux-test-role.json
- test-app/src/main/ml-data/jane.json
- test-app/src/main/ml-modules/transforms/redacter.sjs
- test-app/src/main/ml-schemas/redaction/collections.properties
- test-app/src/main/ml-schemas/redaction/email.json
- test-app/src/main/ml-schemas/redaction/permissions.properties
Added the docs to the export area, as I think it's far more likely to redact on export than on import.
> MLE-16430 Added test and docs on using redaction

- docs/export/export-documents.md
- docs/import/import-files/generic-files.md
- flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesExporter.java
- flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesImporter.java
Plus a couple cute little "since" annotations.
> Added docs for streaming

- .gitignore
- CONTRIBUTING.md
- docker-compose.yml
- flux-cli/build.gradle
- flux-cli/src/test/java/com/marklogic/flux/AbstractTest.java
- flux-cli/src/test/java/com/marklogic/flux/api/OrcFilesImporterTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/ErrorMessagesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportOrcFilesTest.java
Fixed some existing issues too
> Upgrading Sonar

- flux-cli/src/main/java/com/marklogic/flux/impl/OptionsUtil.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ImportFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesTest.java
- flux-cli/src/test/resources/xml-file/namespaced-java-client-intro.xml
This is just adding the bare minimum to a single command for easy demo'ing.
> Initial splitter support

- flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParamsImpl.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/copy/CopyTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateJsonFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateXmlFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportArchiveFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAvroFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportJdbcTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportMlcpArchiveFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportOrcFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportParquetFilesTest.java
Except for RDF, where it doesn't make any sense.
> MLE-16820 All import commands support splitting now

- docs/import/import-files/json.md
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAggregateJsonFilesTest.java
> Added missing docs for ignore-null-fields for JSON

- flux-cli/build.gradle
See notes in build.gradle for more info.
> MLE-17470 Bumped zookeeper to remove log4j 1.x dependency

- docs/api.md
- docs/getting-started.md
- docs/spark-integration.md
- examples/client-project/build.gradle
- flux-cli/build.gradle
- gradle.properties
This addresses the single issue of removing the log4j 1 dependency.
> Merge 1.1.3 into main

- docs/import/import-files/json.md
This will go to main and then get merged to develop.
> MLE-17292 Added docs note about JSON array support

- docs/import/splitting.md
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/splitter/ImportAndSplitFilesTest.java
Also renamed an option so it's clear what the namespace refers to.
> Finished adding descriptions to each new splitter param

- flux-custom-splitter-example/README.md
- flux-custom-splitter-example/build.gradle
- flux-custom-splitter-example/src/main/java/org/example/EnronEmailSplitter.java
- settings.gradle
The README is temporary - the real docs will provide better details on how to do this.
> MLE-17529 Example of a custom splitter

- docs/reprocess.md
> Added examples of reader/writer for reprocessing docs

- docs/export/export-archives.md
- docs/import/import-files/archives.md
- examples/client-project/build.gradle
- examples/client-project/src/main/java/org/example/App.java
Also updated client-project App to depend on the Getting Started example application.
> Small doc fixes

- docs/import/embedder.md
- docs/import/handling-errors.md
- docs/import/splitting.md
- docs/import/tuning-performance.md
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/EmbedderParams.java
Will likely tweak this a bit before release, but this gets 90% of it done.
> MLE-17914 Docs for embedder

- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java
> Disabling odd test on Mac

- CONTRIBUTING.md
- Jenkinsfile
- build.gradle
- docker-compose.yml
- flux-cli/build.gradle
- flux-cli/src/dist/conf/log4j2.properties
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/EmbedderParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/embedder/ImportFilesWithEmbedderTest.java
- flux-cli/src/test/resources/log4j2.properties
- flux-embedding-model-azure-open-ai/build.gradle
- flux-embedding-model-ollama/build.gradle
- flux-embedding-model-ollama/src/main/java/com/marklogic/flux/langchain4j/embedding/OllamaEmbeddingModelFunction.java
- flux-embedding-model-ollama/src/test/java/com/marklogic/flux/langchain4j/embedding/OllamaConfigTest.java
- flux-embedding-model-ollama/src/test/resources/logback.xml
- settings.gradle
Also found a better way to ensure we use the right version of Jackson.
> MLE-17947: Added support for Ollama

- docs/import/embedder/embedding-query.md
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesTest.java
Also fixed random docs issue I saw this morning.
> MLE-19124 Added test for export path not existing

- docs/reprocess.md
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/EmbedderParams.java
- flux-cli/src/test/java/com/marklogic/flux/api/GenericFilesImporterTest.java
Also sneaking in note about reprocess and when thread count may need to be zero.
> MLE-19191 Fixing issue with embedder class name

- flux-cli/build.gradle
- flux-cli/src/main/java/com/marklogic/flux/api/SplitterOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/SplitterParams.java
- flux-cli/src/test/java/com/marklogic/flux/api/ClassifierOptionsTest.java
- test-app/.gitignore
This probably isn't 100% complete yet. It probably needs more tests at the least.
> Can now request that chunks get classified during the splitting process.

- build.gradle
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportAvroFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportParquetFilesTest.java
- flux-java17-tests/build.gradle
And somehow I started getting compilation issues for java17-tests too, so fixed that.
> Fixing a couple Sonar warnings

- flux-cli/src/main/java/com/marklogic/flux/api/ClassifierOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ClassifierParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ImportFilesCommand.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ClassifierOptionsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java
> Fixing extraction and classifier

- flux-cli/src/main/java/com/marklogic/flux/api/ClassifierOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ClassifierParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ClassifierOptionsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ExtractTextTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAndClassifyFilesOptionsTest.java
- flux-java17-tests/src/test/java/com/marklogic/flux/impl/importdata/ImportWithAllProcessingTest.java
- flux-tests-api/build.gradle
Added test for extracting / splitting / embedding. Holding off on classifying for now, want to see if there's a way to mock S4.
> Updated based on change to "path" from "endpoint"

- docs/import/import-files/delimited-text.md
Pushing this to main to get the docs updated immediately.
> MLE-19663 Docs update for delimited files

- flux-cli/build.gradle
- flux-cli/src/dist/conf/log4j2.properties
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ExtractTextTest.java
- flux-custom-splitter-example/build.gradle
- flux-embedding-model-azure-open-ai/build.gradle
- flux-embedding-model-minilm/build.gradle
- flux-embedding-model-ollama/build.gradle
- flux-java17-tests/build.gradle
- flux-tests-api/build.gradle
- gradle.properties
Also tweaked the logging for Semaphore to align to what the connector uses for logger names.
> Added Gradle properties to control common versions

- Jenkinsfile
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ExtractTextTest.java
- flux-java17-tests/src/test/java/com/marklogic/flux/impl/importdata/ImportWithAllProcessingTest.java
Restoring tests in Jenkinsfile, hoping pipeline works now.
> Updating extraction tests

- flux-custom-splitter-example/src/main/java/org/example/EnronEmailSplitter.java
- gradle.properties
This won't work until the Spark connector is published
> Upgraded langchain4j

- docs/import/import-files/json.md
Based on a debugging session I just did
> Added docs on failing fast with JSON lines files

- docs/import/import-files/delimited-text.md
There just isn't a good way to do this with Spark other than ingesting each file separately.
> MLE-19663 Better docs for files with different columns

- docker-compose.yml
May as well knock this out as well.
> Prepend the docker stack for Sameera.

- docs/import/classifier.md
- docs/import/embedder/embedder.md
- docs/import/handling-errors.md
- docs/import/splitting.md
- docs/import/tuning-performance.md
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ClassifierTest.java
Need to add another option from the connector. Updated the test based on CLI option names.
> MLE-21002 First batch of classifier docs

- docs/import/common-import-features.md
Based on user misunderstanding.
> Added clarification for how a REST transform works

- flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
- flux-cli/src/test/java/com/marklogic/flux/impl/copy/CopyOptionsTest.java
- flux-tests-api/src/main/java/com/marklogic/flux/AbstractFluxTest.java
Hadn't finished the test for pipeline batch size.
> Polaris fixes and a bug fix

- flux-cli/src/main/java/com/marklogic/flux/api/WriteDocumentsOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/copy/CopyCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteDocumentParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/copy/CopyOptionsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFilesOptionsTest.java
Just needed to expose command line options and API methods.
> MLE-21267 Can now set metadata values and document properties

- docs/import/common-import-features.md
- flux-cli/src/test/java/com/marklogic/flux/api/GenericFilesImporterTest.java
Also added a smoke test for the extraction options in the API.
> Docs for new options

- docs/common-options.md
- flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
- flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/CommonParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/SparkUtil.java
- flux-cli/src/test/java/com/marklogic/flux/impl/OverrideSparkSessionBuilderTest.java
> Can now specify Spark config options for Session creation

- NOTICE.txt
- docs/getting-started.md
- docs/import/embedder/embedder.md
- docs/import/embedder/embedding-query.md
- docs/spark-integration.md
Will bump actual version on release branch
> Updated NOTICE and version reference in docs

- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
- flux-cli/src/main/java/com/marklogic/flux/tde/JsonTdeBuilder.java
- flux-cli/src/main/java/com/marklogic/flux/tde/TdeBuilder.java
- flux-cli/src/main/java/com/marklogic/flux/tde/TdeInputs.java
- flux-cli/src/main/java/com/marklogic/flux/tde/XmlTdeBuilder.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportJdbcTest.java
- flux-java17-tests/build.gradle
- flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildJsonTdeTest.java
- flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildXmlTdeTest.java
Did some refactoring and added TdeBuilder abstraction with separate JSON and XML implementations. Also shifted to "build" from "generate".
> MLE-21742 Can now build TDE for XML data

- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
- flux-cli/src/main/java/com/marklogic/flux/tde/JsonTdeBuilder.java
- flux-cli/src/main/java/com/marklogic/flux/tde/TdeBuilder.java
- flux-cli/src/main/java/com/marklogic/flux/tde/TdeTemplate.java
- flux-cli/src/main/java/com/marklogic/flux/tde/XmlTdeBuilder.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportJdbcTest.java
- flux-java17-tests/build.gradle
- flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildJsonTdeTest.java
- flux-java17-tests/src/test/java/com/marklogic/flux/tde/BuildXmlTdeTest.java
This doesn't complete the story, but I realized it would help a lot if TdeBuilder returns an AbstractWriteHandle, which easily plugs into an eval call.
There's a big TODO on making an actual connection to load the TDE. This PR is just to get the refactor of TdeBuilder in place.
> MLE-21745 Refactor: Improved TdeBuilder interface

- flux-cli/src/main/java/com/marklogic/flux/api/TdeOptions.java
- flux-cli/src/main/java/com/marklogic/flux/api/WriteStructuredDocumentsOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/TdeParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/WriteStructuredDocumentParams.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportDelimitedFilesOptionsTest.java
To make this a bit nicer, moved all the TDE params into a new TdeParams class so it can easily implement TdeOptions. Copilot did most of the work here.
> MLE-21825 Added support for TDE options in API

- flux-cli/src/main/java/com/marklogic/flux/cli/Main.java
- flux-cli/src/test/java/com/marklogic/flux/AbstractTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/HelpTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/OverrideSparkConfTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/VersionTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportAvroFilesTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/importdata/ImportFromS3Test.java
- flux-java17-tests/src/test/java/com/marklogic/flux/AbstractJava17Test.java
- flux-tests-api/src/main/java/com/marklogic/flux/AbstractFluxTest.java
Using picocli's support for overriding stdout.
> MLE-21825 Refactored tests that assert on stdout

- .env
- Jenkinsfile
- docker-compose.yml
- flux-cli/src/test/java/com/marklogic/flux/CopyrightTest.java
> MLE-12345 Fix to avoid checkout errors in Jenkins

- docs/import/import-files/selecting-files.md
- docs/import/import.md
Will likely improve these as this feature is tested more.
> MLE-22615 First cut at docs

- flux-cli/src/main/java/com/marklogic/flux/api/AzureStorageOptions.java
- flux-cli/src/main/java/com/marklogic/flux/api/CustomExportWriteOptions.java
- flux-cli/src/main/java/com/marklogic/flux/api/GenericFilesExporter.java
- flux-cli/src/main/java/com/marklogic/flux/api/ReadFilesOptions.java
- flux-cli/src/main/java/com/marklogic/flux/api/WriteFilesOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/AzureStorageParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/custom/AbstractCustomExportCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/custom/CustomImportCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/AbstractExportRowsToFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/CloudStorageWriteOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportArchiveFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportRdfFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/WriteFilesParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/WriteStructuredFilesParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/AbstractImportFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ReadFilesParams.java
- flux-cli/src/test/java/com/marklogic/flux/api/OrcFilesImporterTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/AzureStorageOptionsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/AzureStorageParamsTest.java
- flux-cli/src/test/java/com/marklogic/flux/impl/export/ExportFilesAzureTest.java
Larger blast radius than I was hoping, as I needed to convert the 6 Azure params into an AzureStorageOptions interface instead of duplicating them in 4 new classes.
> MLE-22953 Can now export files to Azure

- flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/CloudStorageParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/custom/AbstractCustomExportCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/custom/CustomImportCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/AbstractExportRowsToFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/CloudStorageWriteOptions.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportArchiveFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/ExportRdfFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/export/WriteFilesParams.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/AbstractImportFilesCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/importdata/ReadFilesParams.java
Cuts down on some duplication across import/export with Azure.
> MLE-22953 Refactor: Extracted CloudStorageParams

- docs/import/tuning-performance.md
Applying this to main branch to get docs updated immediately.
> MLE-23140 Added docs for pipeline batch size

- build.gradle
- docs/export/specifying-path.md
- flux-tests-api/build.gradle
Tossing in a couple bumps to make BD happy too.
> MLE-23378 Added note about file paths

- flux-cli/src/main/java/com/marklogic/flux/impl/AbstractCommand.java
- flux-cli/src/main/java/com/marklogic/flux/impl/VersionCommand.java
- flux-cli/src/test/java/com/marklogic/flux/impl/VersionTest.java
Making Jos Happy Again.
Also tweaking some code that Polaris is incorrectly complaining could throw an NPE, in the hope that the tweak will make Polaris not be incorrect.
> MLE-24488 Added aliases for version command
